version: '3'
services:

  myapp-postgres:
    image: postgres:alpine
    container_name: ecom_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5433:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - myapp

  ecom_api:
    container_name: ecom_api
    image: my-go-app  # replace with your image name and tag
    ports: 
      - 8089:8080 
    restart: on-failure
    depends_on:
      - myapp-postgres       
    networks:
      - myapp
    
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - myapp-postgres
    ports:
      - "5050:80"
    networks:
      - myapp
    restart: unless-stopped

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  myapp:
    driver: bridge

